[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools==73.0.1", "wheel==0.44.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixeltable-pgserver"
version = "0.2.7"
description = "Embedded Postgres Server for Pixeltable"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
urls={repository="https://github.com/pixeltable/pixeltable-pgserver"}
authors=[{ name="Pixeltable, Inc.", email="contact@pixeltable.com" }]
keywords=["postgresql", "pgvector", "pgserver", "pixeltable", "rag"]
dependencies = [
    "fasteners>=0.19",
    "platformdirs>=4.0.0",
    "psutil>=5.9.0",
]

[project.optional-dependencies]
dev = [
    "sysv_ipc",
]
test = [
    "pytest",
    "psycopg2-binary==2.9.9",
    "psycopg[binary]==3.1.18",
    "sqlalchemy>=2",
    "sqlalchemy-utils"
]

[tool.isort]
line_length = 120

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["pixeltable_pgserver*"]  # package names should match these glob patterns (["*"] by default)

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.cibuildwheel]
before-all = "make"
test-extras = "test"
test-command = "bash -x {project}/cibuildwheel_test.bash {project}"

[tool.cibuildwheel.linux]
before-all = "yum install -y readline-devel; make"
